spring:
  main:
    allow-bean-definition-overriding: true
  application: 
    name: mg-node-sys
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: mg
  datasource: 
    password: shineon@1234
    driverclassname: com.mysql.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/mg.frame.sys?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai"
    username: root
  redis: 
    host: 127.0.0.1
    port: 6379
    database: 0
server: 
  port: 11001
logging: 
  level: 
    root: info
  file:  ../mg.log/mg.node.sys.log
mg:
  version: 20200520
eureka: 
  client: 
    serviceurl: 
      defaultZone: "http://127.0.0.1:15101/eureka"
  instance:
    prefer-ip-address: true
    
curator:
  retryCount: 5  #重试次数
  elapsedTimeMs: 5000   #重试间隔时间
  connectString: 106.55.154.105:2181   # zookeeper 地址
  sessionTimeoutMs: 60000  # session超时时间
  connectionTimeoutMs: 5000  # 连接超时时间

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
