spring:
  main:
    allow-bean-definition-overriding: true
  application: 
    name: mg-compose-uums
  session: 
    timeout: 3600s
    redis: 
      namespace: 
        spring: session
      flushmode: on_save
    storetype: redis
  servlet: 
    multipart: 
      resolvelazily: true
      maxrequestsize: 6000MB
      location: "c:/tmp"
      filesizethreshold: 2000
      maxfilesize: 6000MB
  redis: 
    host: 127.0.0.1
    port: 6379
    database: 0
  cloud:
    stream:
      bindings:
        MataoMessageOutput:
          destination: MataoMessage
        MataoMessageInput:
          destination: MataoMessage
  rabbit :
    bindings:
      input:
        consumer:
          autoBindDlq: true #启用死信队列，默认会生成一个DLX EXCHANGE，当消息重复消费失败后
          #死信队列配置，可不给值
          #dlqTtl: 5000 #死信队列 消息存放时间 ，最好不要设置不然消息将会丢弃
          dlqDeadLetterExchange: matao.DLX  #如果该列声明，那么deadLetterExchange也要声明，这个保持一致
          deadLetterExchange: matao.DLX #与dlqDeadLetterExchange保持一致
          deadLetterQueueName: matao.dlq #死信队列名称，可不给值，默认prefix+destination.dlq
          #死信队列配置，可不给值
          republishToDlq: true #该值为false如果设置了死信队列，消息对原封不动的发送到死信队列，如果为true，则消息对带上错误信息发送至死信队列
          requeueRejected: true #默认false，只能抛AmqpRejectAndDontRequeueException消息才能到死信队列，如果为true，所有错误消息都会抛到死信队列
          #prefix: feign-test2 #声明exchange、queue前缀
          #bindingRoutingKey: feign-test.destination 默认为#，如果是动态binding模式，producer发送的routingKey 默认为destination
  rabbitmq:
    addresses: 127.0.0.1
    password: matao
    publisherconfirms: true
    port: 5672
    username: matao

server: 
  port: 12001
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 5000
        timeout: 
          enabled: true
eureka: 
  client: 
    serviceurl: 
      defaultZone: "http://127.0.0.1:15101/eureka"
  instance:
    prefer-ip-address: true

ribbon:
  ConnectTimeout: 3000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  ReadTimeout: 3000
  OkToRetryOnAllOperations: false
logging: 
  level: 
    root: info
  file: ../mg.log/mg.compose.uums.log
feign: 
  hystrix: 
    enabled: true

curator:
  retryCount: 5  #重试次数
  elapsedTimeMs: 5000   #重试间隔时间
  connectString: 106.55.154.105:2181   # zookeeper 地址
  sessionTimeoutMs: 60000  # session超时时间
  connectionTimeoutMs: 5000  # 连接超时时间
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false